config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  get '/about', to: 'static_pages#about'
  
  resources :users
  get '/signup',to:'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :microposts, only: [:index,:create, :destroy]
  root 'microposts#index'

end

app/views/layouts/_header.html.erb
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        
        <nav>
          <!--这是logo  -->
          <%= link_to image_tag("Micro Post.png", alt: "Micro Post"),root_path,id:"logo" %>
          <%= link_to "天天微博",root_path,id:"logo" %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "首页",root_path %></li>
            
            <% if logged_in? %> <!--若已登录-->
              
              <li class="dropdown"> 
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 个人 <b class="caret"></b> </a> 
                <ul class="dropdown-menu"> 
                  <li><%= link_to "个人微博", current_user %></li> 
                  <li><%= link_to "帐号设置", edit_user_path(current_user) %></li> 
                  <li class="divider"></li> 
                  <li><%= link_to "查看所有用户", users_path %></li> <!--该行可以删除？？-->
                  <li class="divider"></li> 
                  <li> <%= link_to "退出登录", logout_path, method: "delete" %> </li> 
                </ul> 
              </li> 
            <% else %> <!--若未登录-->
              <li><%= link_to "登录", login_path %></li> 
              <li><%= link_to "注册", signup_path %></li>
            <% end %> 
            <li><%= link_to "关于", about_path %></li>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_shim.html.erb
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!--这是模板文件  -->
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/shim' %><!--render(view, locals, buffer=nil, &block)，Render a template. If the template was not compiled yet, it is done exactly before rendering.  -->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <!-- 其他view的内容被自动引入到这里 -->
      <%= yield %>
      
      <%= debug(params) if Rails.env.development? %><!-- 仅开发环境显示 -->
    </div>
    

  </body>
</html>